name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (Data Processing)
        run: |
          cd data-processing-service
          pip install -r requirements.txt
          cd ..

      - name: Install dependencies (Simulation)
        run: |
          cd simulation-service
          pip install -r requirements.txt
          cd ..

      - name: Run unit tests (Data Processing)
        run: |
          cd data-processing-service
          pytest --maxfail=1 --disable-warnings -q
          cd ..

      - name: Run unit tests (Simulation)
        run: |
          cd simulation-service
          pytest --maxfail=1 --disable-warnings -q
          cd ..

      - name: Docker build
        run: |
          docker build -t data-processing-service:latest ./data-processing-service
          docker build -t simulation-service:latest ./simulation-service

  integration-test:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose version || curl -SL https://get.docker.com/ | sh

      - name: Build and run services
        run: |
          docker-compose up -d --build

          sleep 5


          curl -f http://localhost:5001/configs

          curl -f -X POST -H "Content-Type: application/json" \
               -d '{"config_id": 1, "algorithm": "ant_colony"}' \
               http://localhost:5002/simulate

      - name: Tear down
        run: |
          docker-compose down
